trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: which g++ && g++ --version
        displayName: 'Check GCC version'
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml

  - job: 'win2016_vs2017_cmake312'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
        parameters:
          cmake: 'C:\cmake\bin\cmake'
          ctest: 'C:\cmake\bin\ctest'

  - job: 'macos1013_xcode91_cmake313'
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
