trigger:
  - master
  - develop
  - azure-pipelines

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: which g++ && g++ --version
        displayName: 'Check GCC version'
      - script: which cmake && cmake --version
        displayName: 'Check CMake version'
      - script: cmake -H. -B_build
        displayName: 'Run CMake to configure build'
      - script: cmake --build _build
        displayName: 'Run CMake to build'
      - script: cd _build && ctest -V
        displayName: 'Run CTest to test'
