trigger:
  branches:
    include:
    - develop
    - master
    - bugfix/*
    - feature/*
    - fix/*
    - ml/*
    - pr/*

stages:
- stage: Test
  jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        GCC 5:
          TOOLSET: gcc-5
    steps:
    - bash: |
        set -e
        source install.sh
        echo "step install - original SELF       before task.setvariable: SELF=$SELF"
        echo "step install - original BOOST_ROOT before task.setvariable: BOOST_ROOT=$BOOST_ROOT"
        # AzP predefines BOOST_ROOT, so we need this gymnastics to override it with ours.
        # AzP requires to run special task in order to export
        # BOOST_ROOT and others as job-scoped variable from a script.
        #
        echo "SELF=$SELF"
        echo "BOOST_ROOT=$BOOST_ROOT"
        # Comment
        echo "##vso[task.setvariable variable=SELF]$SELF"
        echo "##vso[task.setvariable variable=BOOST_ROOT]$BOOST_ROOT"
        # Comment
        echo "##vso[task.setvariable variable=SELF1]$SELF"
        echo "##vso[task.setvariable variable=BOOST_ROOT1]$BOOST_ROOT"
        #
        echo "##vso[task.setvariable variable=SELF2]"$SELF
        echo "##vso[task.setvariable variable=BOOST_ROOT2]"$BOOST_ROOT
      displayName: 'Install'
    - bash: |
        set -e
        echo "step build - overriden: SELF=$SELF"
        echo "step build - overriden: BOOST_ROOT=$BOOST_ROOT"
        echo "step build - variant 1: SELF1=$SELF1"
        echo "step build - variant 1: BOOST_ROOT1=$BOOST_ROOT1"
        echo "step build - variant 2: SELF2=$SELF2"
        echo "step build - variant 2: BOOST_ROOT2=$BOOST_ROOT2"
        ls $BOOST_ROOT
        ls $BOOST_ROOT1
        ls $BOOST_ROOT2
      displayName: 'Build'
  - job: 'Windows'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        VS 2017 C++17:
          TOOLSET: msvc-14.1
    steps:
    - script: |
        set SELF=%BUILD_REPOSITORY_NAME:-=_%
        for /f "tokens=2 delims=/" %%a in ("%SELF%") do set SELF=%%a
        set BOOST_ROOT=%BUILD_SOURCESDIRECTORY%\boost-root

        echo ##vso[task.setvariable variable=SELF]%SELF%
        echo ##vso[task.setvariable variable=BOOST_ROOT]%BOOST_ROOT%
      displayName: 'Install'
    - script: |
        echo "step build - overriden: SELF=%SELF%"
        echo "step build - overriden: BOOST_ROOT=%BOOST_ROOT%"
        set
      displayName: 'Build'
