language: cpp

before_install:
  - ./bin/ci/before_install.sh

before_script:
  - ./bin/ci/before_script.sh

script:
  - ./bin/ci/script.sh

after_script:
  - echo "Finished"

matrix:
  include:
    - env: FEATURE=1 CXXFLAGS=-m32
      compiler: gcc
      addons:
        mariadb: "10.0"
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packges:
            - g++-5
            - libboost-locale1.55-dev
