language: cpp
compiler:
    - gcc
    - clang
env:
    matrix:
        - FEATURE=1
        - FEATURE=2
        - FEATURE=3
script:
    - echo "FEATURE=$FEATURE"
    - make check
    - sh ./test.sh
after_script:
    - echo "TRAVIS_TEST_RESULT=${TRAVIS_TEST_RESULT}"
