os:
  - linux
  - windows

language: cpp

script:
  - cmake --version
  - g++ --version
  - make --version
  - cl --version
  - nmake --version
  - call '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64'
  - cl --version
  - nmake --version
