language: cpp
compiler:
    - gcc
    - clang
env:
    matrix:
        - FEATURE=1
        - FEATURE=2
        - FEATURE=3
script:
    - echo "FEATURE=$FEATURE"
    - ./script.sh

after_script:
    - echo "FEATURE=$FEATURE"
