language: cpp

before_install:
  - ./bin/ci/before_install.sh

before_script:
  - ./bin/ci/before_script.sh

script:
  - ./bin/ci/script.sh

after_script:
  - echo "Finished"

matrix:
  include:
    - env: FEATURE=1 CXXFLAGS=-m32
      compiler: gcc
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-locale1.55-dev
    - env: FEATURE=1 CXXFLAGS=-m64
      compiler: gcc
      addons: &gcc5
    - env: FEATURE=2 CC=i586-mingw32msvc-gcc CXX=i586-mingw32msvc-g++ LD=i586-mingw32msvc-ld
    - env: FEATURE=3 SOCI_TRAVIS_BACKEND=oracle