dist: precise
sudo: required

language: cpp

script:
  - cmake --version
  - g++ --version
  - curl --silent -o cmake-linux.sh https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.sh
  - ls -l
  - sudo sh cmake-linux.sh -- --skip-license --prefix=/usr/local
  - cmake --version

