os:
  - linux
  #- windows

language: cpp

ref:
  sources: &sources
    - ubuntu-toolchain-r-test

before_install:
  - ./.ci/install-cmake.sh $HOME/usr
  - export PATH=$HOME/usr/bin:$PATH

before_script:
  - cmake --version
  - g++ --version
  - mkdir -p ${TRAVIS_BUILD_DIR}/_build

script:
  - cd ${TRAVIS_BUILD_DIR}/_build
  - mkdir -p ${TRAVIS_BUILD_DIR}/_install
  - cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/_install ${TRAVIS_BUILD_DIR}
  - cmake --build .
  - ctest -V --output-on-failure
