language: cpp
compiler:
    - gcc
      #- clang
env:
    - FEATURE=1 CXXFLAGS=-m32
    - FEATURE=1 CXXFLAGS=-m64
    - FEATURE=2
    - FEATURE=3

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-multilib

script:
    - echo "FEATURE=$FEATURE"
    - ./script.sh

after_script:
    - echo "FEATURE=$FEATURE"
