version: 2
jobs:
  build:
    working_directory: ~/ci-test
    docker:
      - image: gcc:latest
    steps:
      - run:
          name: Install dependencies ci-test
          command: apt-get update && apt-get install -y cmake
      - checkout
      - run:
          name: Configure ci-test
          command: pwd && mkdir -p build && cd build && cmake ..
      - run:
          name: Build ci-test
          command: pwd && cmake --build .
      - run:
          name: Test ci-test
          command: pwd && find && file test && ldd test && ./test && file test2 && ldd test2
