steps:
  - script: sudo sh .ci/install-cmake.sh
    displayName: 'Install CMake'
    condition: eq(variables['Agent.OS'], 'Linux')
  - powershell: ./.ci/install-cmake.ps1
    displayName: 'Install CMake'
    condition: eq(variables['Agent.OS'], 'Windows_NT')
  - script: |
      wget https://cmake.org/files/v3.13/cmake-3.13.2-Darwin-x86_64.tar.gz
      tar -xzf cmake-3.13.2-Darwin-x86_64.tar.gz
      sudo mv cmake-3.8.1-Darwin-x86_64/CMake.app /Applications
      sudo /Applications/CMake.app/Contents/bin/cmake-gui --install
    displayName: 'Install CMake'
    condition: eq(variables['Agent.OS'], 'macOS')
