name: Greet Everyone
on: [push]

jobs:
  greet-job:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print a greeting
        env:
          MY_VAR: My name is
          FIRST_NAME: CI
          LAST_NAME: Test
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME.
